name: Frontend CI
on:
    push:
        # path: "apps/front/**"
    pull_request:
        # path: "apps/front/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: pnpm install
              working-directory: apps/front

            - name: Run tests
              run: pnpm test
              working-directory: apps/front

            - name: Build project
              run: pnpm run build
              working-directory: apps/front

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Deploy to production
              run: echo "Triggering deployment..."
