name: Frontend CI
on:
    push:
        paths:
            - "apps/front/**"
    pull_request:
        paths:
            - "apps/front/**"

jobs:
    build:
        defaults:
            run:
                working-directory: apps/front

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 10
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: pnpm install

            - name: Run tests
              run: pnpm test:ci

            - name: Build project
              run: pnpm run build

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Deploy to production
              run: |
                  curl \
                  --request GET '${{ secrets.DEPLOY_URL }}' \
                  --header 'Authorization: Bearer ${{ secrets.DEPLOY_SECRET }}'
